[2023-10-01T12:56:56.811+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Milestone3.cleaning_data manual__2023-10-01T12:56:53.859355+00:00 [queued]>
[2023-10-01T12:56:56.824+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Milestone3.cleaning_data manual__2023-10-01T12:56:53.859355+00:00 [queued]>
[2023-10-01T12:56:56.825+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-10-01T12:56:56.826+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2023-10-01T12:56:56.827+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-10-01T12:56:56.844+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): cleaning_data> on 2023-10-01 12:56:53.859355+00:00
[2023-10-01T12:56:56.849+0000] {standard_task_runner.py:52} INFO - Started process 414 to run task
[2023-10-01T12:56:56.852+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Milestone3', 'cleaning_data', 'manual__2023-10-01T12:56:53.859355+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_maulana_priadhi_gajadi.py', '--cfg-path', '/tmp/tmpqqed6zl6', '--error-file', '/tmp/tmp_o4p8e8b']
[2023-10-01T12:56:56.854+0000] {standard_task_runner.py:80} INFO - Job 20: Subtask cleaning_data
[2023-10-01T12:56:56.925+0000] {task_command.py:371} INFO - Running <TaskInstance: Milestone3.cleaning_data manual__2023-10-01T12:56:53.859355+00:00 [running]> on host 7f9228e255c3
[2023-10-01T12:56:57.005+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maulana
AIRFLOW_CTX_DAG_ID=Milestone3
AIRFLOW_CTX_TASK_ID=cleaning_data
AIRFLOW_CTX_EXECUTION_DATE=2023-10-01T12:56:53.859355+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-01T12:56:53.859355+00:00
[2023-10-01T12:56:57.008+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_maulana_priadhi_gajadi.py", line 98, in cleaning_data
    df = pd.read_csv('/opt/airflow/dags/P2M3_maulana_priadhi_data_raw.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/P2M3_maulana_priadhi_data_raw.csv'
[2023-10-01T12:56:57.029+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=Milestone3, task_id=cleaning_data, execution_date=20231001T125653, start_date=20231001T125656, end_date=20231001T125657
[2023-10-01T12:56:57.044+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task cleaning_data ([Errno 2] No such file or directory: '/opt/airflow/dags/P2M3_maulana_priadhi_data_raw.csv'; 414)
[2023-10-01T12:56:57.067+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-01T12:56:57.116+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
